ARG NODE_VERSION=26-slim
ARG PORT=5000

FROM node:${NODE_VERSION} AS runtime

WORKDIR /app

RUN chown node:node /app

USER node

COPY --chown=node:node server/package*.json ./

RUN npm ci

COPY --chown=node:node server/ ./

EXPOSE ${PORT}

CMD ["npm", "run", "start:dev"]
